import { type JewelleryProduct } from "@/components/JewelleryCard";
import randomImg1 from "@/assets/random-img-1.webp";
import randomImg2 from "@/assets/random-img-2.webp";
import randomImg3 from "@/assets/random-img-3.webp";
import randomImg4 from "@/assets/random-img-4.webp";
import randomImg5 from "@/assets/random-img-5.webp";

// Map jewellery assets to authentic Raajsi product photography (random-img-1 to 5)
const jewelleryHero = randomImg1;
const jewelleryRings = randomImg2;
const jewelleryMens = randomImg3;
const jewelleryNecklace = randomImg4;
const jewelleryBangles = randomImg5;

export const MOCK_JEWELLERY_PRODUCTS: JewelleryProduct[] = [
  // ── RINGS (min 3) ───────────────────────────────────────────────────
  {
    id: "ring-1",
    slug: "royal-solitaire-kundan-ring",
    title: "Royal Kundan Solitaire Ring",
    medium: "22K Yellow Gold",
    story: "Handcrafted in Jaipur with an uncut diamond (Polki) set in gold foil surrounded by brilliant enamel work.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryHero, jewelleryRings],
    availability: "available",
    price_min: 28500,
    price_max: 28500,
    display_price: 28500,
    price_display: "fixed",
    metadata: {
      material: "22K Yellow Gold",
      finishing: "High Polish Gold",
      length: "N/A",
      width: "14 mm",
      thickness: "2 mm",
      gemstone: "Uncut Polki Diamond & Ruby",
      ring_size: "14",
      ring_sizes: ["10", "12", "14", "16", "18", "20"],
      subcategory: "Rings",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryHero, jewelleryRings, jewelleryMens],
    },
  },
  {
    id: "ring-2",
    slug: "mens-regal-gold-signet-ring",
    title: "Men's Regal Lion Signet Ring",
    medium: "18K Yellow Gold",
    story: "Bold signet ring featuring hand-carved Rajput crest details and solid gold weight designed for men.",
    primary_image_url: jewelleryMens,
    gallery_image_urls: [jewelleryRings, jewelleryMens],
    availability: "available",
    price_min: 42000,
    price_max: 42000,
    display_price: 42000,
    price_display: "fixed",
    metadata: {
      material: "18K Gold",
      finishing: "Matte & Polished Crest",
      length: "N/A",
      width: "18 mm",
      thickness: "3 mm",
      gemstone: "Natural Black Onyx",
      ring_size: "18",
      ring_sizes: ["14", "16", "18", "20", "22"],
      subcategory: "Rings",
      gender: "men",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryMens],
    },
  },
  {
    id: "ring-3",
    slug: "unisex-hammered-silver-band",
    title: "Hand-Hammered Silver Band Ring",
    medium: "925 Sterling Silver",
    story: "Textured unisex silver band hand-hammered by Jaipur artisans, suitable for everyday understated elegance.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryHero, jewelleryRings],
    availability: "available",
    price_min: 4800,
    price_max: 4800,
    display_price: 4800,
    price_display: "fixed",
    metadata: {
      material: "925 Sterling Silver",
      finishing: "Antique Hammered Finish",
      length: "N/A",
      width: "8 mm",
      thickness: "2 mm",
      gemstone: "None",
      ring_size: "16",
      ring_sizes: ["10", "12", "14", "16", "18", "20"],
      subcategory: "Rings",
      gender: "unisex",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryHero, jewelleryRings],
    },
  },

  // ── CHAINS (min 3) ──────────────────────────────────────────────────
  {
    id: "chain-1",
    slug: "heritage-gold-rope-chain",
    title: "Heritage 22K Gold Twisted Rope Chain",
    medium: "22K Yellow Gold",
    story: "Classic 22-inch twisted gold chain crafted with dense weight and secure S-hook clasp.",
    primary_image_url: jewelleryHero,
    gallery_image_urls: [jewelleryHero, jewelleryRings],
    availability: "available",
    price_min: 78000,
    price_max: 78000,
    display_price: 78000,
    price_display: "fixed",
    metadata: {
      material: "22K Gold",
      finishing: "High Polish",
      length: "22 Inches",
      width: "4.5 mm",
      thickness: "4.5 mm",
      gemstone: "None",
      subcategory: "Chains",
      gender: "unisex",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryHero, jewelleryRings],
    },
  },
  {
    id: "chain-2",
    slug: "mens-heavy-box-silver-chain",
    title: "Men's Heavy Sterling Silver Box Chain",
    medium: "925 Sterling Silver",
    story: "Robust 24-inch oxidized silver chain with geometric box links, tailored for daily masculine wear.",
    primary_image_url: jewelleryMens,
    gallery_image_urls: [jewelleryMens, jewelleryHero],
    availability: "available",
    price_min: 9500,
    price_max: 9500,
    display_price: 9500,
    price_display: "fixed",
    metadata: {
      material: "925 Sterling Silver",
      finishing: "Oxidized Antique Silver",
      length: "24 Inches",
      width: "5.5 mm",
      thickness: "5.5 mm",
      gemstone: "None",
      subcategory: "Chains",
      gender: "men",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryMens, jewelleryHero],
    },
  },
  {
    id: "chain-3",
    slug: "womens-delicate-pearl-gold-chain",
    title: "Women's Pearl Chintak Gold Chain",
    medium: "18K Yellow Gold",
    story: "Graceful gold chain interwoven with natural Basra pearls and gemstone drops.",
    primary_image_url: jewelleryHero,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 36000,
    price_max: 36000,
    display_price: 36000,
    price_display: "fixed",
    metadata: {
      material: "18K Gold",
      finishing: "Polished Gold",
      length: "18 Inches",
      width: "3 mm",
      thickness: "2 mm",
      gemstone: "Freshwater Pearls & Emerald Beads",
      subcategory: "Chains",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },

  // ── BRACELETS (min 3) ───────────────────────────────────────────────
  {
    id: "bracelet-1",
    slug: "kundan-filigree-cuff-bracelet",
    title: "Kundan Filigree Gold Cuff Bracelet",
    medium: "22K Yellow Gold",
    story: "Openable gold cuff encrusted with green emeralds and floral Kundan foil settings.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryHero, jewelleryRings],
    availability: "available",
    price_min: 64000,
    price_max: 64000,
    display_price: 64000,
    price_display: "fixed",
    metadata: {
      material: "22K Gold",
      finishing: "Antique Gold & Enamel",
      length: "7.5 Inches",
      width: "16 mm",
      thickness: "3 mm",
      gemstone: "Zambian Emerald & Polki",
      subcategory: "Bracelets",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryHero, jewelleryRings],
    },
  },
  {
    id: "bracelet-2",
    slug: "mens-braided-leather-gold-clasp-bracelet",
    title: "Men's Braided Leather & 18K Gold Clasp Bracelet",
    medium: "18K Gold & Genuine Italian Leather",
    story: "Contemporary dark brown leather weave fastened with a precision-machined 18K gold magnetic clasp.",
    primary_image_url: jewelleryMens,
    gallery_image_urls: [jewelleryMens, jewelleryHero],
    availability: "available",
    price_min: 19500,
    price_max: 19500,
    display_price: 19500,
    price_display: "fixed",
    metadata: {
      material: "18K Gold & Leather",
      finishing: "Satin Brushed Gold",
      length: "8 Inches",
      width: "10 mm",
      thickness: "6 mm",
      gemstone: "None",
      subcategory: "Bracelets",
      gender: "men",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryMens, jewelleryHero],
    },
  },
  {
    id: "bracelet-3",
    slug: "unisex-silver-curb-link-bracelet",
    title: "Unisex Sterling Silver Curb Link Bracelet",
    medium: "925 Sterling Silver",
    story: "Solid curb chain bracelet hand-polished with double locking lobster clasp.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 7200,
    price_max: 7200,
    display_price: 7200,
    price_display: "fixed",
    metadata: {
      material: "925 Sterling Silver",
      finishing: "High Polish Silver",
      length: "8 Inches",
      width: "8 mm",
      thickness: "3 mm",
      gemstone: "None",
      subcategory: "Bracelets",
      gender: "unisex",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },

  // ── EARRINGS (min 3) ────────────────────────────────────────────────
  {
    id: "earring-1",
    slug: "jaipur-kundan-jhumka-earrings",
    title: "Jaipur Bridal Kundan Jhumka Earrings",
    medium: "22K Yellow Gold",
    story: "Traditional dome jhumkas featuring pearl cluster drops and green Meenakari detailing on the inner cap.",
    primary_image_url: jewelleryHero,
    gallery_image_urls: [jewelleryHero, jewelleryRings],
    availability: "available",
    price_min: 52000,
    price_max: 52000,
    display_price: 52000,
    price_display: "fixed",
    metadata: {
      material: "22K Gold",
      finishing: "Meenakari & High Polish",
      length: "2.8 Inches",
      width: "22 mm",
      thickness: "N/A",
      gemstone: "Natural Pearls & Ruby Beads",
      subcategory: "Earrings",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryHero, jewelleryRings],
    },
  },
  {
    id: "earring-2",
    slug: "polki-chandbali-royal-earrings",
    title: "Royal Polki Chandbali Earrings",
    medium: "22K Yellow Gold",
    story: "Crescent-shaped Chandbali earrings set with uncut diamond Polkis and ruby cabochons.",
    primary_image_url: jewelleryHero,
    gallery_image_urls: [jewelleryHero, jewelleryRings],
    availability: "available",
    price_min: 68000,
    price_max: 68000,
    display_price: 68000,
    price_display: "fixed",
    metadata: {
      material: "22K Gold",
      finishing: "Antique Gold",
      length: "3.2 Inches",
      width: "35 mm",
      thickness: "N/A",
      gemstone: "Uncut Polki & Burma Rubies",
      subcategory: "Earrings",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryHero, jewelleryRings],
    },
  },
  {
    id: "earring-3",
    slug: "unisex-diamond-solitaire-studs",
    title: "Unisex Gold Diamond Solitaire Studs",
    medium: "18K White Gold",
    story: "Minimalist 4-prong diamond stud earrings with screw-back posts for security.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 24500,
    price_max: 24500,
    display_price: 24500,
    price_display: "fixed",
    metadata: {
      material: "18K White Gold",
      finishing: "Rhodium Polish",
      length: "0.5 Inches",
      width: "6 mm",
      thickness: "N/A",
      gemstone: "VVS Diamonds (0.50 CTW)",
      subcategory: "Earrings",
      gender: "unisex",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },

  // ── BANGLES (min 3) ─────────────────────────────────────────────────
  {
    id: "bangle-1",
    slug: "meenakari-enamel-gold-bangle-set",
    title: "Jaipur Royal Meenakari Gold Bangle Pair",
    medium: "22K Yellow Gold",
    story: "Set of 2 handcrafted gold bangles embellished with red and green floral enamel work.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryHero, jewelleryRings],
    availability: "available",
    price_min: 94000,
    price_max: 94000,
    display_price: 94000,
    price_display: "fixed",
    metadata: {
      material: "22K Gold",
      finishing: "Hand-painted Enamel & Gold",
      length: "N/A",
      width: "12 mm",
      thickness: "3 mm",
      gemstone: "Polki Accents",
      subcategory: "Bangles",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryHero, jewelleryRings],
    },
  },
  {
    id: "bangle-2",
    slug: "silver-filigree-chudi-bangles",
    title: "Heritage Sterling Silver Filigree Bangles (Set of 4)",
    medium: "925 Sterling Silver",
    story: "Four slender silver bangles featuring intricate Rajasthani filigree wirework.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 12500,
    price_max: 12500,
    display_price: 12500,
    price_display: "fixed",
    metadata: {
      material: "925 Sterling Silver",
      finishing: "Oxidized Silver",
      length: "N/A",
      width: "6 mm each",
      thickness: "2 mm",
      gemstone: "None",
      subcategory: "Bangles",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },
  {
    id: "bangle-3",
    slug: "unisex-solid-silver-gokharu-bangle",
    title: "Unisex Solid Silver Gokharu Bangle",
    medium: "925 Sterling Silver",
    story: "Traditional Gokharu design silver bangle with studded geometric motifs.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 8900,
    price_max: 8900,
    display_price: 8900,
    price_display: "fixed",
    metadata: {
      material: "925 Sterling Silver",
      finishing: "High Polish",
      length: "N/A",
      width: "10 mm",
      thickness: "4 mm",
      gemstone: "None",
      subcategory: "Bangles",
      gender: "unisex",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },

  // ── PENDANTS (min 3) ────────────────────────────────────────────────
  {
    id: "pendant-1",
    slug: "emerald-cut-kundan-gold-pendant",
    title: "Imperial Zambian Emerald Kundan Pendant",
    medium: "22K Yellow Gold",
    story: "Oval natural emerald centerpiece encapsulated in Kundan gold work with pearl drop tassel.",
    primary_image_url: jewelleryHero,
    gallery_image_urls: [jewelleryHero, jewelleryRings],
    availability: "available",
    price_min: 44000,
    price_max: 44000,
    display_price: 44000,
    price_display: "fixed",
    metadata: {
      material: "22K Gold",
      finishing: "High Polish Gold",
      length: "2.2 Inches",
      width: "25 mm",
      thickness: "5 mm",
      gemstone: "Natural Emerald & Seed Pearls",
      subcategory: "Pendants",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryHero, jewelleryRings],
    },
  },
  {
    id: "pendant-2",
    slug: "mens-gold-om-swastik-pendant",
    title: "Men's Solid Gold Sacred Medallion Pendant",
    medium: "18K Yellow Gold",
    story: "Engineered solid gold medallion featuring relief carvings of traditional protective motifs.",
    primary_image_url: jewelleryMens,
    gallery_image_urls: [jewelleryMens, jewelleryHero],
    availability: "available",
    price_min: 29500,
    price_max: 29500,
    display_price: 29500,
    price_display: "fixed",
    metadata: {
      material: "18K Gold",
      finishing: "Satin & Polished Relief",
      length: "1.5 Inches",
      width: "20 mm",
      thickness: "2.5 mm",
      gemstone: "Single Diamond Accent",
      subcategory: "Pendants",
      gender: "men",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryMens, jewelleryHero],
    },
  },
  {
    id: "pendant-3",
    slug: "unisex-silver-yantra-locket-pendant",
    title: "Unisex Sterling Silver Geometry Locket Pendant",
    medium: "925 Sterling Silver",
    story: "Openable silver locket with sacred geometry engraving and velvet interior.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 6200,
    price_max: 6200,
    display_price: 6200,
    price_display: "fixed",
    metadata: {
      material: "925 Sterling Silver",
      finishing: "Oxidized Silver",
      length: "1.8 Inches",
      width: "22 mm",
      thickness: "6 mm",
      gemstone: "None",
      subcategory: "Pendants",
      gender: "unisex",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },

  // ── ANKLETS (min 3) ─────────────────────────────────────────────────
  {
    id: "anklet-1",
    slug: "traditional-silver-ghungroo-payal",
    title: "Traditional Silver Ghungroo Payal Anklet Pair",
    medium: "925 Sterling Silver",
    story: "Pair of heavy silver anklets decorated with musical ghungroo bells and filigree clasp.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 14500,
    price_max: 14500,
    display_price: 14500,
    price_display: "fixed",
    metadata: {
      material: "925 Sterling Silver",
      finishing: "Antique Silver",
      length: "10.5 Inches",
      width: "14 mm",
      thickness: "4 mm",
      gemstone: "None",
      subcategory: "Anklets",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },
  {
    id: "anklet-2",
    slug: "delicate-gold-chain-anklet",
    title: "Women's 18K Gold Minimalist Charm Anklet",
    medium: "18K Yellow Gold",
    story: "Slender gold chain anklet featuring dangling star and droplet charms.",
    primary_image_url: jewelleryHero,
    gallery_image_urls: [jewelleryHero, jewelleryRings],
    availability: "available",
    price_min: 21000,
    price_max: 21000,
    display_price: 21000,
    price_display: "fixed",
    metadata: {
      material: "18K Gold",
      finishing: "High Polish",
      length: "9.5 Inches (Adjustable)",
      width: "3 mm",
      thickness: "1.5 mm",
      gemstone: "Cubic Zirconia Accents",
      subcategory: "Anklets",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryHero, jewelleryRings],
    },
  },
  {
    id: "anklet-3",
    slug: "unisex-black-thread-silver-anklet",
    title: "Unisex Black Thread & Silver Knot Anklet",
    medium: "925 Sterling Silver & Silk Thread",
    story: "Durable woven silk thread anklet with silver beads and protective evil eye charm.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 2800,
    price_max: 2800,
    display_price: 2800,
    price_display: "fixed",
    metadata: {
      material: "925 Silver & Thread",
      finishing: "Polished Silver Beads",
      length: "10 Inches",
      width: "4 mm",
      thickness: "3 mm",
      gemstone: "Turquoise Bead",
      subcategory: "Anklets",
      gender: "unisex",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },

  // ── NOSE RINGS (min 3) ──────────────────────────────────────────────
  {
    id: "nose-1",
    slug: "bridal-pearl-kundan-nath",
    title: "Jaipur Bridal Kundan Nath Nose Ring",
    medium: "22K Yellow Gold",
    story: "Ornate bridal nose ring (Nath) with single strand pearl chain, Kundan flower, and teardrop ruby.",
    primary_image_url: jewelleryHero,
    gallery_image_urls: [jewelleryHero, jewelleryRings],
    availability: "available",
    price_min: 31000,
    price_max: 31000,
    display_price: 31000,
    price_display: "fixed",
    metadata: {
      material: "22K Gold",
      finishing: "High Polish",
      length: "Chain: 7 Inches",
      width: " Ring: 28 mm",
      thickness: "1.2 mm",
      gemstone: "Basra Pearls & Ruby",
      subcategory: "Nose Rings",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryHero, jewelleryRings],
    },
  },
  {
    id: "nose-2",
    slug: "minimal-gold-septum-ring",
    title: "Handcrafted 18K Gold Septum Nose Ring",
    medium: "18K Yellow Gold",
    story: "Pierced or clip-on minimalist gold septum ring with beaded granules.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 11500,
    price_max: 11500,
    display_price: 11500,
    price_display: "fixed",
    metadata: {
      material: "18K Gold",
      finishing: "Satin Polish",
      length: "N/A",
      width: "12 mm",
      thickness: "1 mm",
      gemstone: "None",
      subcategory: "Nose Rings",
      gender: "women",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },
  {
    id: "nose-3",
    slug: "unisex-silver-clip-on-nose-pin",
    title: "Unisex Tribal Silver Clip-On Nose Stud",
    medium: "925 Sterling Silver",
    story: "Non-pierced tribal silver nose pin with floral stamping.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 1900,
    price_max: 1900,
    display_price: 1900,
    price_display: "fixed",
    metadata: {
      material: "925 Sterling Silver",
      finishing: "Oxidized Silver",
      length: "N/A",
      width: "6 mm",
      thickness: "1 mm",
      gemstone: "None",
      subcategory: "Nose Rings",
      gender: "unisex",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },

  // ── KADAS (min 3) ───────────────────────────────────────────────────
  {
    id: "kada-1",
    slug: "mens-heavy-22k-gold-rajputi-kada",
    title: "Men's Heavy 22K Gold Rajputi Elephant Kada",
    medium: "22K Yellow Gold",
    story: "Substantial 22K gold kada featuring hand-chased elephant head terminals (Hathi Mukhi).",
    primary_image_url: jewelleryMens,
    gallery_image_urls: [jewelleryMens, jewelleryHero],
    availability: "available",
    price_min: 145000,
    price_max: 145000,
    display_price: 145000,
    price_display: "fixed",
    metadata: {
      material: "22K Gold",
      finishing: "Antique Hand Chased",
      length: "N/A",
      width: "18 mm",
      thickness: "8 mm",
      gemstone: "Ruby Eyes",
      subcategory: "Kadas",
      gender: "men",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryMens, jewelleryHero],
    },
  },
  {
    id: "kada-2",
    slug: "mens-solid-silver-faceted-kada",
    title: "Men's Solid Sterling Silver Faceted Chissa Kada",
    medium: "925 Sterling Silver",
    story: "Solid silver kada with hand-cut diamond facets that reflect light with every movement.",
    primary_image_url: jewelleryMens,
    gallery_image_urls: [jewelleryMens, jewelleryRings],
    availability: "available",
    price_min: 16500,
    price_max: 16500,
    display_price: 16500,
    price_display: "fixed",
    metadata: {
      material: "925 Sterling Silver",
      finishing: "Diamond Faceted Polish",
      length: "N/A",
      width: "14 mm",
      thickness: "6 mm",
      gemstone: "None",
      subcategory: "Kadas",
      gender: "men",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryMens, jewelleryRings],
    },
  },
  {
    id: "kada-3",
    slug: "unisex-copper-silver-dual-tone-kada",
    title: "Unisex Dual-Tone Silver & Copper Wellness Kada",
    medium: "925 Sterling Silver & Pure Copper",
    story: "Twisted dual-metal kada combining silver and copper for traditional wellness and balance.",
    primary_image_url: jewelleryRings,
    gallery_image_urls: [jewelleryRings, jewelleryHero],
    availability: "available",
    price_min: 5500,
    price_max: 5500,
    display_price: 5500,
    price_display: "fixed",
    metadata: {
      material: "Silver & Pure Copper",
      finishing: "Brushed Dual Tone",
      length: "N/A",
      width: "10 mm",
      thickness: "4 mm",
      gemstone: "None",
      subcategory: "Kadas",
      gender: "unisex",
      stock: "In Stock (Ready to Ship)",
      gallery_images: [jewelleryRings, jewelleryHero],
    },
  },
];
