/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookVisitRouteImport } from './routes/book-visit'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as InquireRouteImport } from './routes/inquire'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MuseumRouteImport } from './routes/museum'
import { Route as PressRouteImport } from './routes/press'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as ArtworksSlugRouteImport } from './routes/artworks.$slug'
import { Route as ExhibitionsSlugRouteImport } from './routes/exhibitions.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as PoliciesDocRouteImport } from './routes/policies.$doc'
import { Route as AdminAdminAcquisitionsRouteImport } from './routes/_admin/admin/acquisitions'
import { Route as AdminAdminAppointmentsRouteImport } from './routes/_admin/admin/appointments'
import { Route as AdminAdminArtistsRouteImport } from './routes/_admin/admin/artists'
import { Route as AdminAdminArtworksRouteImport } from './routes/_admin/admin/artworks'
import { Route as AdminAdminAuditLogsRouteImport } from './routes/_admin/admin/audit-logs'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AdminAdminInquiriesRouteImport } from './routes/_admin/admin/inquiries'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin/orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVisitRoute = BookVisitRouteImport.update({
  id: '/book-visit',
  path: '/book-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const InquireRoute = InquireRouteImport.update({
  id: '/inquire',
  path: '/inquire',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumRoute = MuseumRouteImport.update({
  id: '/museum',
  path: '/museum',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksSlugRoute = ArtworksSlugRouteImport.update({
  id: '/artworks/$slug',
  path: '/artworks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsSlugRoute = ExhibitionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExhibitionsRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const PoliciesDocRoute = PoliciesDocRouteImport.update({
  id: '/policies/$doc',
  path: '/policies/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminAcquisitionsRoute = AdminAdminAcquisitionsRouteImport.update({
  id: '/admin/acquisitions',
  path: '/admin/acquisitions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminAppointmentsRoute = AdminAdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminArtistsRoute = AdminAdminArtistsRouteImport.update({
  id: '/admin/artists',
  path: '/admin/artists',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminArtworksRoute = AdminAdminArtworksRouteImport.update({
  id: '/admin/artworks',
  path: '/admin/artworks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminAuditLogsRoute = AdminAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminInquiriesRoute = AdminAdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-visit': typeof BookVisitRoute
  '/collection': typeof CollectionRoute
  '/commissions': typeof CommissionsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRouteWithChildren
  '/inquire': typeof InquireRoute
  '/journal': typeof JournalRouteWithChildren
  '/museum': typeof MuseumRoute
  '/press': typeof PressRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visit': typeof VisitRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/artworks/$slug': typeof ArtworksSlugRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/policies/$doc': typeof PoliciesDocRoute
  '/artists/': typeof ArtistsIndexRoute
  '/admin/acquisitions': typeof AdminAdminAcquisitionsRoute
  '/admin/appointments': typeof AdminAdminAppointmentsRoute
  '/admin/artists': typeof AdminAdminArtistsRoute
  '/admin/artworks': typeof AdminAdminArtworksRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/inquiries': typeof AdminAdminInquiriesRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-visit': typeof BookVisitRoute
  '/collection': typeof CollectionRoute
  '/commissions': typeof CommissionsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRouteWithChildren
  '/inquire': typeof InquireRoute
  '/journal': typeof JournalRouteWithChildren
  '/museum': typeof MuseumRoute
  '/press': typeof PressRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visit': typeof VisitRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/artworks/$slug': typeof ArtworksSlugRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/policies/$doc': typeof PoliciesDocRoute
  '/artists': typeof ArtistsIndexRoute
  '/admin/acquisitions': typeof AdminAdminAcquisitionsRoute
  '/admin/appointments': typeof AdminAdminAppointmentsRoute
  '/admin/artists': typeof AdminAdminArtistsRoute
  '/admin/artworks': typeof AdminAdminArtworksRoute
  '/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/inquiries': typeof AdminAdminInquiriesRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-visit': typeof BookVisitRoute
  '/collection': typeof CollectionRoute
  '/commissions': typeof CommissionsRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/exhibitions': typeof ExhibitionsRouteWithChildren
  '/inquire': typeof InquireRoute
  '/journal': typeof JournalRouteWithChildren
  '/museum': typeof MuseumRoute
  '/press': typeof PressRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visit': typeof VisitRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/artworks/$slug': typeof ArtworksSlugRoute
  '/exhibitions/$slug': typeof ExhibitionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/policies/$doc': typeof PoliciesDocRoute
  '/artists/': typeof ArtistsIndexRoute
  '/_admin/admin/acquisitions': typeof AdminAdminAcquisitionsRoute
  '/_admin/admin/appointments': typeof AdminAdminAppointmentsRoute
  '/_admin/admin/artists': typeof AdminAdminArtistsRoute
  '/_admin/admin/artworks': typeof AdminAdminArtworksRoute
  '/_admin/admin/audit-logs': typeof AdminAdminAuditLogsRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/inquiries': typeof AdminAdminInquiriesRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book-visit'
    | '/collection'
    | '/commissions'
    | '/compare'
    | '/contact'
    | '/exhibitions'
    | '/inquire'
    | '/journal'
    | '/museum'
    | '/press'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/visit'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/wishlist'
    | '/artists/$slug'
    | '/artworks/$slug'
    | '/exhibitions/$slug'
    | '/journal/$slug'
    | '/policies/$doc'
    | '/artists/'
    | '/admin/acquisitions'
    | '/admin/appointments'
    | '/admin/artists'
    | '/admin/artworks'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/inquiries'
    | '/admin/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book-visit'
    | '/collection'
    | '/commissions'
    | '/compare'
    | '/contact'
    | '/exhibitions'
    | '/inquire'
    | '/journal'
    | '/museum'
    | '/press'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/visit'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/wishlist'
    | '/artists/$slug'
    | '/artworks/$slug'
    | '/exhibitions/$slug'
    | '/journal/$slug'
    | '/policies/$doc'
    | '/artists'
    | '/admin/acquisitions'
    | '/admin/appointments'
    | '/admin/artists'
    | '/admin/artworks'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/inquiries'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book-visit'
    | '/collection'
    | '/commissions'
    | '/compare'
    | '/contact'
    | '/exhibitions'
    | '/inquire'
    | '/journal'
    | '/museum'
    | '/press'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/visit'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/wishlist'
    | '/artists/$slug'
    | '/artworks/$slug'
    | '/exhibitions/$slug'
    | '/journal/$slug'
    | '/policies/$doc'
    | '/artists/'
    | '/_admin/admin/acquisitions'
    | '/_admin/admin/appointments'
    | '/_admin/admin/artists'
    | '/_admin/admin/artworks'
    | '/_admin/admin/audit-logs'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/inquiries'
    | '/_admin/admin/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookVisitRoute: typeof BookVisitRoute
  CollectionRoute: typeof CollectionRoute
  CommissionsRoute: typeof CommissionsRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  ExhibitionsRoute: typeof ExhibitionsRouteWithChildren
  InquireRoute: typeof InquireRoute
  JournalRoute: typeof JournalRouteWithChildren
  MuseumRoute: typeof MuseumRoute
  PressRoute: typeof PressRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisitRoute: typeof VisitRoute
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  ArtworksSlugRoute: typeof ArtworksSlugRoute
  PoliciesDocRoute: typeof PoliciesDocRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-visit': {
      id: '/book-visit'
      path: '/book-visit'
      fullPath: '/book-visit'
      preLoaderRoute: typeof BookVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquire': {
      id: '/inquire'
      path: '/inquire'
      fullPath: '/inquire'
      preLoaderRoute: typeof InquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museum': {
      id: '/museum'
      path: '/museum'
      fullPath: '/museum'
      preLoaderRoute: typeof MuseumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks/$slug': {
      id: '/artworks/$slug'
      path: '/artworks/$slug'
      fullPath: '/artworks/$slug'
      preLoaderRoute: typeof ArtworksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions/$slug': {
      id: '/exhibitions/$slug'
      path: '/$slug'
      fullPath: '/exhibitions/$slug'
      preLoaderRoute: typeof ExhibitionsSlugRouteImport
      parentRoute: typeof ExhibitionsRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/policies/$doc': {
      id: '/policies/$doc'
      path: '/policies/$doc'
      fullPath: '/policies/$doc'
      preLoaderRoute: typeof PoliciesDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/acquisitions': {
      id: '/_admin/admin/acquisitions'
      path: '/admin/acquisitions'
      fullPath: '/admin/acquisitions'
      preLoaderRoute: typeof AdminAdminAcquisitionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/appointments': {
      id: '/_admin/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAdminAppointmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/artists': {
      id: '/_admin/admin/artists'
      path: '/admin/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminAdminArtistsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/artworks': {
      id: '/_admin/admin/artworks'
      path: '/admin/artworks'
      fullPath: '/admin/artworks'
      preLoaderRoute: typeof AdminAdminArtworksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/audit-logs': {
      id: '/_admin/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/inquiries': {
      id: '/_admin/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminAdminInquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminAcquisitionsRoute: typeof AdminAdminAcquisitionsRoute
  AdminAdminAppointmentsRoute: typeof AdminAdminAppointmentsRoute
  AdminAdminArtistsRoute: typeof AdminAdminArtistsRoute
  AdminAdminArtworksRoute: typeof AdminAdminArtworksRoute
  AdminAdminAuditLogsRoute: typeof AdminAdminAuditLogsRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminInquiriesRoute: typeof AdminAdminInquiriesRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminAcquisitionsRoute: AdminAdminAcquisitionsRoute,
  AdminAdminAppointmentsRoute: AdminAdminAppointmentsRoute,
  AdminAdminArtistsRoute: AdminAdminArtistsRoute,
  AdminAdminArtworksRoute: AdminAdminArtworksRoute,
  AdminAdminAuditLogsRoute: AdminAdminAuditLogsRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminInquiriesRoute: AdminAdminInquiriesRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ExhibitionsRouteChildren {
  ExhibitionsSlugRoute: typeof ExhibitionsSlugRoute
}

const ExhibitionsRouteChildren: ExhibitionsRouteChildren = {
  ExhibitionsSlugRoute: ExhibitionsSlugRoute,
}

const ExhibitionsRouteWithChildren = ExhibitionsRoute._addFileChildren(
  ExhibitionsRouteChildren,
)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookVisitRoute: BookVisitRoute,
  CollectionRoute: CollectionRoute,
  CommissionsRoute: CommissionsRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  ExhibitionsRoute: ExhibitionsRouteWithChildren,
  InquireRoute: InquireRoute,
  JournalRoute: JournalRouteWithChildren,
  MuseumRoute: MuseumRoute,
  PressRoute: PressRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisitRoute: VisitRoute,
  ArtistsSlugRoute: ArtistsSlugRoute,
  ArtworksSlugRoute: ArtworksSlugRoute,
  PoliciesDocRoute: PoliciesDocRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
